#stage 1 build
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app
COPY ["/app/dockerpractice/dockerpractice.csproj","/dockerpractice"]
RUN dotnet restore 'dockerpractice/dockerpractice.csproj'
#stage 2 publish
COPY ["/app/dockerpractice", "/dockerpractice"]
RUN dotnet publish -c Release -o out
#stage 3 run
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
EXPOSE 80
ENTRYPOINT ["dotnet", "dockerpractice.dll"]